version: '3.8'

services:
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    image: devanajonnsson/viaserra-portal:1.0-26174730
    container_name: viaserra-portal
    ports:
      - "8030:80"
    restart: always

  manutencao:
    build:
      context: ./manutencao
      dockerfile: Dockerfile
    image: devanajonnsson/viaserra-manutencao:1.0-26174730
    container_name: viaserra-manutencao
    ports:
      - "7030:80"
    restart: always